### PR TITLE
adding dist to repo, allows installing directly from the repo

### PR DESCRIPTION
**Pull request by sramam**
Currently, master branch seems too be 5 months behind the published npm-version.
Committing the dist directory to the repo allows easily installing from the git repo without
installing all the dev-dependencies. 

Possible solution for #7

### CODE REVIEW

**Comment by domoritz** [comment]
I am making releases to https://github.com/vega/typescript-to-json-schema/tree/release and tag versions.

You can just use 

```
"typescript-to-json-schema": "vega/typescript-to-json-schema#v0.8.0",
```

in your package.json.

**Comment by sramam** [comment]
Interesting. So what's the issue with having this in the master branch then?

It affords the same convenience to the active development stream - in my case, I am using this library as a dependency in another module. Finding an issue in use, coming back to this module and then needing to test it in the other. 

Admittedly, this is only an issue when in active development. Once I know what I want, I'd use a unit test case to solve the issue.

The only issue I have found with committing the dist directory to the repo is actually remembering to commit the changes. I ran into this frequently enough that I wrote up https://github.com/sramam/git-mods. 

It can simply be used as a run-script or chained together with other commands to ensure that 

1. all local mods are staged before commit.
2. all local mods are committed before pushing. 


```

"devDependencies": {
   ...
   "git-mods": "^1.0.7",
   "husky": "^0.14.3",
   ...
},
"scripts: {
  ...
  "precommit": "git-mods --staged_ok",
  "prepush": "git-mods",
  ...
}
```

**Comment by sramam** [comment]
:) Yes. 
Except that if you don't accept my PRs, I am limited to using my fork- in production. 

By itself, that's just semantics - but installing from branches via npm requires tagging on a continual basis, a PITA. 

In any event, for now, I have a fork with dist committed in my fork, which solves my problem.

So may this PR RIP.

**Comment by domoritz** [comment]
I am accepting pull requests, just not one that adds compiled files because I make the releases on a release branch. Quite the opposite, I am very happy about pull requests! The reason why npm is old is that I am not the maintainer of the npm package and don't have any permissions to make a release.

**Comment by sramam** [comment]
I intend for this to be my last comment on this thread.

You have been most welcoming and responsive. I owe you my unqualified thanks for that and the work you have put into the project.

I needed a solution to my immediate problem - which required an ability install a customized version of the module in my project. By having a fork that does essentially what you do in the release branch, I achieved my purpose. 

While I respect your opinion, mine differs, but only slightly!

**Comment by domoritz** [comment]
Thank you so much for helping with this project and explaining why you prefer to have this change. I always like to hear what workflows work best for other people. Given that this came up, and it doesn't look like my changes won't get merged back, I will reprioritize #7.

Looking forward to future collaborations!

**Pull request closed without merging**
